# Generated by Django 3.2.13 on 2022-11-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='movies')),
                ('category', models.CharField(choices=[('A', 'Hành Động'), ('D', 'DRAMA'), ('S', 'Viễn Tưởng'), ('M', 'Trinh Thám')], max_length=1)),
                ('status', models.CharField(choices=[('RA', 'Gần Đây'), ('MW', 'Xem Nhiều Nhất'), ('TR', 'Lựa Chọn Hàng Đầu')], max_length=3)),
                ('year_of_production', models.DateField()),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='movies')),
            ],
        ),
    ]
