# Generated by Django 3.2.13 on 2022-11-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20221112_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Hành Động', 'Hành Động'), ('DRAMA', 'DRAMA'), ('Viễn Tưởng', 'Viễn Tưởng'), ('Trinh Thám', 'Trinh Thám')], max_length=10),
        ),
    ]
