# Generated by Django 3.2.13 on 2022-11-12 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 18, 18, 40, 931242, tzinfo=utc)),
        ),
    ]
