# Generated by Django 3.2.13 on 2022-11-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_movie_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='flim',
            field=models.FileField(default='', upload_to='movies'),
            preserve_default=False,
        ),
    ]
