# Generated by Django 3.2.5 on 2022-11-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20221115_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='subtitle',
            field=models.FileField(blank=True, upload_to='subs'),
        ),
    ]
