# Generated by Django 3.2.5 on 2022-11-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_alter_movie_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='banner',
            field=models.ImageField(blank=True, upload_to='movies_banner'),
        ),
    ]
