# Generated by Django 3.2.5 on 2022-11-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_alter_movie_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imbd',
            field=models.FloatField(null=True),
        ),
    ]
